#include "base/Axi.h"

namespace project_xs::sim {

AxiLiteIf::AxiLiteIf(std::uint32_t* awaddr_ptr,
                     bool* awvalid_ptr,
                     bool* awready_ptr,
                     std::uint32_t* wdata_ptr,
                     bool* wvalid_ptr,
                     bool* wready_ptr,
                     std::uint8_t* bresp_ptr,
                     bool* bvalid_ptr,
                     bool* bready_ptr,
                     std::uint32_t* araddr_ptr,
                     bool* arvalid_ptr,
                     bool* arready_ptr,
                     std::uint32_t* rdata_ptr,
                     std::uint8_t* rresp_ptr,
                     bool* rvalid_ptr,
                     bool* rready_ptr)
    : awaddr(RegPort::make_output<std::uint32_t>("axil_awaddr", awaddr_ptr)),
      awvalid(WirePort::make_output<bool>("axil_awvalid", awvalid_ptr)),
      awready(WirePort::make_input<bool>("axil_awready", awready_ptr)),
      wdata(RegPort::make_output<std::uint32_t>("axil_wdata", wdata_ptr)),
      wvalid(WirePort::make_output<bool>("axil_wvalid", wvalid_ptr)),
      wready(WirePort::make_input<bool>("axil_wready", wready_ptr)),
      bresp(RegPort::make_input<std::uint8_t>("axil_bresp", bresp_ptr)),
      bvalid(WirePort::make_input<bool>("axil_bvalid", bvalid_ptr)),
      bready(WirePort::make_output<bool>("axil_bready", bready_ptr)),
      araddr(RegPort::make_output<std::uint32_t>("axil_araddr", araddr_ptr)),
      arvalid(WirePort::make_output<bool>("axil_arvalid", arvalid_ptr)),
      arready(WirePort::make_input<bool>("axil_arready", arready_ptr)),
      rdata(RegPort::make_input<std::uint32_t>("axil_rdata", rdata_ptr)),
      rresp(RegPort::make_input<std::uint8_t>("axil_rresp", rresp_ptr)),
      rvalid(WirePort::make_input<bool>("axil_rvalid", rvalid_ptr)),
      rready(WirePort::make_output<bool>("axil_rready", rready_ptr)) {}

AxiStreamIf::AxiStreamIf(std::uint64_t* tdata_ptr,
                         bool* tvalid_ptr,
                         bool* tready_ptr,
                         bool* tlast_ptr)
    : tdata(WirePort::make_output<std::uint64_t>("axis_tdata", tdata_ptr)),
      tvalid(WirePort::make_output<bool>("axis_tvalid", tvalid_ptr)),
      tready(WirePort::make_input<bool>("axis_tready", tready_ptr)),
      tlast(tlast_ptr ? WirePort::make_output<bool>("axis_tlast", tlast_ptr) : nullptr) {}

AxiMasterIf::AxiMasterIf(std::uint64_t* araddr_ptr,
                         bool* arvalid_ptr,
                         bool* arready_ptr,
                         std::uint64_t* rdata_ptr,
                         bool* rvalid_ptr,
                         bool* rready_ptr,
                         bool* rlast_ptr,
                         std::uint64_t* awaddr_ptr,
                         bool* awvalid_ptr,
                         bool* awready_ptr,
                         std::uint64_t* wdata_ptr,
                         bool* wvalid_ptr,
                         bool* wready_ptr,
                         bool* wlast_ptr,
                         std::uint8_t* bresp_ptr,
                         bool* bvalid_ptr,
                         bool* bready_ptr)
    : araddr(RegPort::make_output<std::uint64_t>("axi_araddr", araddr_ptr)),
      arvalid(WirePort::make_output<bool>("axi_arvalid", arvalid_ptr)),
      arready(WirePort::make_input<bool>("axi_arready", arready_ptr)),
      rdata(RegPort::make_input<std::uint64_t>("axi_rdata", rdata_ptr)),
      rvalid(WirePort::make_input<bool>("axi_rvalid", rvalid_ptr)),
      rready(WirePort::make_output<bool>("axi_rready", rready_ptr)),
      rlast(WirePort::make_input<bool>("axi_rlast", rlast_ptr)),
      awaddr(RegPort::make_output<std::uint64_t>("axi_awaddr", awaddr_ptr)),
      awvalid(WirePort::make_output<bool>("axi_awvalid", awvalid_ptr)),
      awready(WirePort::make_input<bool>("axi_awready", awready_ptr)),
      wdata(WirePort::make_output<std::uint64_t>("axi_wdata", wdata_ptr)),
      wvalid(WirePort::make_output<bool>("axi_wvalid", wvalid_ptr)),
      wready(WirePort::make_input<bool>("axi_wready", wready_ptr)),
      wlast(WirePort::make_output<bool>("axi_wlast", wlast_ptr)),
      bresp(RegPort::make_input<std::uint8_t>("axi_bresp", bresp_ptr)),
      bvalid(WirePort::make_input<bool>("axi_bvalid", bvalid_ptr)),
      bready(WirePort::make_output<bool>("axi_bready", bready_ptr)) {}

}  // namespace project_xs::sim
